version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./data/:/var/lib/postgresql/data
